# Generated by Django 3.0 on 2020-08-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Droid',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Character')),
                ('primary_function', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.character',),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('opening_text', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes_by_director', to='api.Person')),
                ('planets', models.ManyToManyField(related_name='episodes_by_planets', to='api.Planet')),
                ('producers', models.ManyToManyField(related_name='episodes_by_producers', to='api.Person')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='appears_in',
            field=models.ManyToManyField(to='api.Episode'),
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Character')),
                ('home_planet', models.CharField(max_length=150)),
                ('friends', models.ManyToManyField(blank=True, to='api.Human')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.character',),
        ),
    ]
